services:
  server:
    container_name: app
    build:
      context: .
    entrypoint: ["sh", "/app/run_app.sh"]
    ports:
      - 8000:8000

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - 8080:8080

  nginx-exporter:
    container_name: nginx-exporter
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - 9113:9113
    command:
      - -nginx.scrape-uri=http://nginx:8000/nginx_status

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000