services:
  app:
    container_name: app
    build:
      context: .
    entrypoint: ["sh", "/app/run_app.sh"]
    ports:
      - 8000:8000

  backend:
    container_name: backend
    image: nginx
    extends:
      service: nginx
    ports:
      - 8080:8080
    volumes:
      - "./nginx.conf:/etc/nginx/backend.nginx.conf"

  edge:
    container_name: edge
    image: nginx
    extends:
      service: nginx
    ports:
      - 8081:8080
    volumes:
      - "./nginx.conf:/etc/nginx/edge.nginx.conf"

  nginx-exporter:
    container_name: nginx-exporter
    image: nginx/nginx-prometheus-exporter:latest
    command:
      - -nginx.scrape-uri=http://nginx:8080/nginx_status

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000