{
 "title": "CDN metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Nginx state",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "rate(nginx_connections_accepted[$__rate_interval])",
     "legendFormat": "Accepted"
    },
    {
     "expr": "rate(nginx_connections_handled[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}